# Generated by Django 5.0.2 on 2024-02-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_winner_anonymous_user_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
