# Generated by Django 5.0.2 on 2024-02-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
