# Generated by Django 5.0.2 on 2024-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_message_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_escrow',
            field=models.BooleanField(default=False),
        ),
    ]
