# Generated by Django 5.0.2 on 2024-03-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_transaction_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, max_length=1080, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transaction', 'Transaction')], default='transaction', max_length=20),
        ),
    ]
