# Generated by Django 5.0.2 on 2024-03-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_transaction_note_transaction_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
