# Generated by Django 5.0.2 on 2024-03-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='local_timezone',
            field=models.CharField(blank=True, default='America/New_York', max_length=64, null=True),
        ),
    ]
