# Generated by Django 5.0.2 on 2024-03-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_user_local_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee_failure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
